# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PizzaApp
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'PizzaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PizzaApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PizzaApp-tvOS

  target 'PizzaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
